<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MEGCP4U" name="HoldActiveCancel_US_main.CreateRequest_Auth" tests="11" failures="1" timestamp="6 Sep 2021 08:14:09 GMT" time="83.457" errors="0">
  <testcase name="skill_Req" time="1.610" classname="HoldActiveCancel_US_main.CreateRequest_Auth"/>
  <testcase name="skill_loc" time="8.674" classname="HoldActiveCancel_US_main.CreateRequest_Auth"/>
  <testcase name="supp" time="21.211" classname="HoldActiveCancel_US_main.CreateRequest_Auth"/>
  <testcase name="RIPC_Login" time="14.706" classname="HoldActiveCancel_US_main.CreateRequest_Auth"/>
  <testcase name="Create_Req" time="1.263" classname="HoldActiveCancel_US_main.CreateRequest_Auth"/>
  <testcase name="reqstatus" time="3.911" classname="HoldActiveCancel_US_main.CreateRequest_Auth">
    <failure type="junit.framework.ComparisonFailure" message="expected:&lt;[Active]&gt; but was:&lt;[Submitted]&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<[Active]> but was:<[Submitted]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at HoldActiveCancel_US.Step01_CreateRequest.supStatus(Step01_CreateRequest.java:597)
	at HoldActiveCancel_US_main.CreateRequest_Auth.reqstatus(CreateRequest_Auth.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- reqstatus -->
  <testcase name="alert_check" time="0.009" classname="HoldActiveCancel_US_main.CreateRequest_Auth"/>
  <testcase name="skill_price" time="6.701" classname="HoldActiveCancel_US_main.CreateRequest_Auth"/>
  <testcase name="select_Req" time="8.582" classname="HoldActiveCancel_US_main.CreateRequest_Auth"/>
  <testcase name="select_jrss" time="3.849" classname="HoldActiveCancel_US_main.CreateRequest_Auth"/>
  <testcase name="req_detail" time="12.941" classname="HoldActiveCancel_US_main.CreateRequest_Auth"/>
</testsuite> <!-- HoldActiveCancel_US_main.CreateRequest_Auth -->
